-- 1. CREACIÓN DE TABLAS MAESTRAS INDEPENDIENTES

CREATE TABLE CITY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL
);

CREATE TABLE TECHNICIAN (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    lastName VARCHAR(50) NOT NULL
);

CREATE TABLE SERVICETYPE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

-- 2. CREACIÓN DE TABLAS MAESTRAS DEPENDIENTES 

CREATE TABLE BRANCH (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    FK_CITY INT,
    FOREIGN KEY (FK_CITY) REFERENCES CITY(ID)
);

CREATE TABLE EQUIPAMENT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    FK_CATEGORY INT,
    FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORY(ID)
);

-- 3. CREACIÓN DE LA TABLA INVOICE

CREATE TABLE INVOICE (
    WorkOrder SERIAL PRIMARY KEY,
    FK_CLIENT SERIAL,
    FK_BRANCH SERIAL,
    FK_TECHNICIAN SERIAL,
    FK_EQUIPAMENT SERIAL,
    FK_SERVICETYPE SERIAL,
    SERVICE_DATE DATE NOT NULL,
    HOURS DECIMAL(5,2) NOT NULL,
    COST DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (FK_CLIENT) REFERENCES CLIENT(ID),
    FOREIGN KEY (FK_BRANCH) REFERENCES BRANCH(ID),
    FOREIGN KEY (FK_TECHNICIAN) REFERENCES TECHNICIAN(ID),
    FOREIGN KEY (FK_EQUIPAMENT) REFERENCES EQUIPAMENT(ID),
    FOREIGN KEY (FK_SERVICETYPE) REFERENCES SERVICETYPE(ID)
);